version: "3.9"
services:
    devweb:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
            - "5003:5000"
        volumes:
            - .:/code 
            - /home:/home 
        deploy:
            resources:
                limits:
                    memory: 10G
        restart: always